from __future__ import annotations

import csv
import itertools
import json
import math
import random
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Sequence

from .solution_sampling import validate_sampling, solution_candidates, select_solution

from .cluster_sampling import (
    AtomRecord,
    FrameData,
    MoleculeRecord,
    Vector,
    _molecule_geometries,
    _unwrapped_molecule_positions,
    add,
    mean_vector,
    minimum_image_delta,
    norm,
    read_gro,
    scale,
    sub,
)


def _progress(enabled: bool, message: str) -> None:
    if enabled:
        print(message, file=sys.stderr, flush=True)


@dataclass
class LammpsDumpFrame:
    frame_index: int
    timestep: int
    positions_nm: list[Vector]
    box_nm: Vector
    forces_ev_ang: list[Vector] | None


@dataclass
class ActiveLearningSample:
    sample_id: int
    cluster_size: int
    frame_index: int
    timestep: int
    molecule_resids: list[int]
    score: float
    max_force_ev_ang: float
    rms_force_ev_ang: float
    min_interatomic_distance_ang: float
    avg_pair_com_distance_ang: float
    avg_contact_count: float
    close_contact_alert: bool
    xyz_path: str | None = None


@dataclass
class _ActiveCandidate:
    frame: LammpsDumpFrame
    mol_indices: tuple[int, ...]
    score: float
    max_force_ev_ang: float
    rms_force_ev_ang: float
    min_interatomic_distance_nm: float
    avg_pair_com_distance_nm: float
    avg_contact_count: float
    close_contact_alert: bool
    compact_score: float
    feature: tuple[float, ...]


def sample_active_learning_clusters(
    dump_path: str | Path,
    reference_gro: str | Path,
    cluster_size: int = 2,
    n_samples: int = 20,
    output_dir: str | Path = "active_learning_samples",
    frame_stride: int = 1,
    max_frames: int | None = None,
    random_frame_samples: int | None = None,
    candidate_seeds_per_frame: int | None = None,
    neighbor_pool: int = 8,
    contact_cutoff_angstrom: float = 5.0,
    close_contact_alert_angstrom: float = 1.2,
    hard_reject_distance_angstrom: float = 0.55,
    random_seed: int = 17,
    write_xyz: bool = True,
    progress: bool = False,
    sampling_mode: str = "film",
    solute_resnames: Sequence[str] = (),
    solvent_resnames: Sequence[str] = (),
    solution_solute_weights: dict[int, float] | None = None,
) -> list[ActiveLearningSample]:
    """Sample MD snapshots that are useful candidates for active learning.

    The sampler reads a LAMMPS custom dump generated by the SevenNet MD input
    and extracts molecular clusters for later DFT labeling. In the absence of
    ensemble/model-deviation uncertainty, it uses practical surrogate signals:
    high force magnitudes, unusually close inter-molecular heavy-atom contacts,
    compact contact-rich clusters, and diversity across frames/geometries.
    """

    if cluster_size < 2:
        raise ValueError("cluster_size must be at least 2")
    if n_samples < 1:
        raise ValueError("n_samples must be at least 1")
    if frame_stride < 1:
        raise ValueError("frame_stride must be at least 1")
    if random_frame_samples is not None and random_frame_samples < 1:
        raise ValueError("random_frame_samples must be at least 1")
    if candidate_seeds_per_frame is not None and candidate_seeds_per_frame < 1:
        raise ValueError("candidate_seeds_per_frame must be at least 1")
    if hard_reject_distance_angstrom < 0.0:
        raise ValueError("hard_reject_distance_angstrom must be non-negative")

    atoms, molecules, _ = read_gro(reference_gro)
    validate_sampling(sampling_mode, solute_resnames, solvent_resnames, solution_solute_weights, molecules)
    frames = read_lammps_dump(
        dump_path,
        frame_stride=frame_stride,
        max_frames=max_frames,
        random_frame_samples=random_frame_samples,
        random_seed=random_seed,
        progress=progress,
    )
    if not frames:
        raise RuntimeError(f"No frames were read from {dump_path}")
    _progress(progress, f"[active-learning] loaded {len(frames)} frame(s) for cluster_size={cluster_size}")

    expected_atoms = len(atoms)
    for frame in frames:
        if len(frame.positions_nm) != expected_atoms:
            raise ValueError(
                f"Frame {frame.frame_index} has {len(frame.positions_nm)} atoms, "
                f"but reference GRO has {expected_atoms}"
            )

    rng = random.Random(random_seed)
    candidates: list[_ActiveCandidate] = []
    for frame_number, frame in enumerate(frames, start=1):
        _progress(
            progress,
            "[active-learning] scoring frame {}/{} for {}mol "
            "(dump_frame={}, step={}, candidates_so_far={})".format(
                frame_number,
                len(frames),
                cluster_size,
                frame.frame_index,
                frame.timestep,
                len(candidates),
            ),
        )
        if sampling_mode == "solution":
            geometry_frame = FrameData(frame.frame_index, None, frame.positions_nm, frame.box_nm)
            geometries = _molecule_geometries(geometry_frame, molecules)
            pair_cache = {}
            for indices in solution_candidates(frame, molecules, cluster_size, neighbor_pool,
                    contact_cutoff_angstrom / 10.0, solute_resnames, solution_solute_weights,
                    rng, candidate_seeds_per_frame):
                candidate = _score_active_candidate(frame, geometry_frame, molecules,
                    geometries, indices, contact_cutoff_angstrom / 10.0,
                    close_contact_alert_angstrom / 10.0,
                    hard_reject_distance_angstrom / 10.0, pair_cache)
                if candidate is not None:
                    candidates.append(candidate)
            continue
        frame_candidates = _frame_active_candidates(
            frame=frame,
            molecules=molecules,
            cluster_size=cluster_size,
            neighbor_pool=neighbor_pool,
            candidate_seeds_per_frame=candidate_seeds_per_frame,
            contact_cutoff_nm=contact_cutoff_angstrom / 10.0,
            close_contact_alert_nm=close_contact_alert_angstrom / 10.0,
            hard_reject_distance_nm=hard_reject_distance_angstrom / 10.0,
            rng=rng,
            progress=progress,
        )
        candidates.extend(frame_candidates)
        _progress(
            progress,
            "[active-learning] finished frame {}/{} for {}mol "
            "(added={}, total_candidates={})".format(
                frame_number,
                len(frames),
                cluster_size,
                len(frame_candidates),
                len(candidates),
            ),
        )

    if not candidates and sampling_mode == "film":
        raise RuntimeError(
            "No active-learning candidates were found. Try increasing "
            "neighbor_pool/contact_cutoff_angstrom or lowering the hard reject distance."
        )

    _progress(progress, f"[active-learning] assigning scores to {len(candidates)} candidate(s)")
    if sampling_mode == "film":
        _assign_active_scores(candidates)
    _progress(progress, f"[active-learning] selecting {n_samples} diverse sample(s)")
    selected = (select_solution(candidates, molecules, solute_resnames, cluster_size,
        solution_solute_weights, n_samples, _select_diverse_active_candidates, output_dir,
        score_group=_assign_active_scores) if sampling_mode == "solution"
        else _select_diverse_active_candidates(candidates, n_samples))

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    _progress(progress, f"[active-learning] writing selected samples to {output_dir}")

    samples: list[ActiveLearningSample] = []
    for sample_id, candidate in enumerate(selected, start=1):
        molecule_resids = [molecules[i].resid for i in candidate.mol_indices]
        xyz_path: str | None = None
        if write_xyz:
            xyz_file = output_dir / (
                f"al_cluster_{cluster_size}mol_{sample_id:04d}_"
                f"step{candidate.frame.timestep:08d}_"
                f"res{'-'.join(str(r) for r in molecule_resids)}.xyz"
            )
            write_active_cluster_xyz(
                xyz_file,
                atoms,
                molecules,
                candidate,
            )
            xyz_path = str(xyz_file)

        samples.append(
            ActiveLearningSample(
                sample_id=sample_id,
                cluster_size=cluster_size,
                frame_index=candidate.frame.frame_index,
                timestep=candidate.frame.timestep,
                molecule_resids=molecule_resids,
                score=candidate.score,
                max_force_ev_ang=candidate.max_force_ev_ang,
                rms_force_ev_ang=candidate.rms_force_ev_ang,
                min_interatomic_distance_ang=candidate.min_interatomic_distance_nm * 10.0,
                avg_pair_com_distance_ang=candidate.avg_pair_com_distance_nm * 10.0,
                avg_contact_count=candidate.avg_contact_count,
                close_contact_alert=candidate.close_contact_alert,
                xyz_path=xyz_path,
            )
        )

    _write_active_metadata(output_dir, samples)
    return samples


def sample_active_learning_clusters_for_sizes(
    dump_path: str | Path,
    reference_gro: str | Path,
    cluster_sizes: Sequence[int],
    n_samples: int,
    output_dir: str | Path = "active_learning_samples",
    **kwargs,
) -> dict[int, list[ActiveLearningSample]]:
    """Sample active-learning candidates for multiple cluster sizes."""

    results: dict[int, list[ActiveLearningSample]] = {}
    for cluster_size in cluster_sizes:
        size_output = Path(output_dir) / f"{cluster_size}mol"
        results[cluster_size] = sample_active_learning_clusters(
            dump_path=dump_path,
            reference_gro=reference_gro,
            cluster_size=cluster_size,
            n_samples=n_samples,
            output_dir=size_output,
            **kwargs,
        )
    return results


def read_lammps_dump(
    path: str | Path,
    frame_stride: int = 1,
    max_frames: int | None = None,
    random_frame_samples: int | None = None,
    random_seed: int = 17,
    progress: bool = False,
) -> list[LammpsDumpFrame]:
    """Read an orthogonal LAMMPS custom dump with x/y/z and optional fx/fy/fz."""

    path = Path(path)
    if random_frame_samples is not None:
        return _read_random_lammps_dump_frames(
            path,
            frame_stride=frame_stride,
            max_frames=max_frames,
            random_frame_samples=random_frame_samples,
            random_seed=random_seed,
            progress=progress,
        )

    frames: list[LammpsDumpFrame] = []
    seen_frames = 0

    with path.open("r", encoding="utf-8") as handle:
        while True:
            line = handle.readline()
            if not line:
                break
            if not line.startswith("ITEM: TIMESTEP"):
                continue

            timestep = int(handle.readline().strip())
            _expect_item(handle.readline(), "ITEM: NUMBER OF ATOMS")
            natoms = int(handle.readline().strip())
            box_header = handle.readline().strip()
            _expect_item(box_header, "ITEM: BOX BOUNDS")
            box_bounds = [_parse_box_bound(handle.readline()) for _ in range(3)]
            box_nm = tuple((hi - lo) / 10.0 for lo, hi in box_bounds)

            atom_header = handle.readline().strip()
            _expect_item(atom_header, "ITEM: ATOMS")
            columns = atom_header.split()[2:]

            if seen_frames % frame_stride != 0:
                for _ in range(natoms):
                    handle.readline()
                seen_frames += 1
                continue

            positions: list[Vector | None] = [None] * natoms
            forces: list[Vector | None] | None = (
                [None] * natoms if all(name in columns for name in ("fx", "fy", "fz")) else None
            )

            col = {name: index for index, name in enumerate(columns)}
            coord_mode = _coordinate_mode(columns)
            for _ in range(natoms):
                parts = handle.readline().split()
                atom_id = int(parts[col["id"]]) - 1
                if atom_id < 0 or atom_id >= natoms:
                    raise ValueError(f"Atom id {atom_id + 1} is outside 1..{natoms}")
                positions[atom_id] = _read_position_nm(parts, col, coord_mode, box_bounds)
                if forces is not None:
                    forces[atom_id] = (
                        float(parts[col["fx"]]),
                        float(parts[col["fy"]]),
                        float(parts[col["fz"]]),
                    )

            if any(pos is None for pos in positions):
                raise ValueError(f"Frame at timestep {timestep} has missing atom ids")

            frame_forces: list[Vector] | None = None
            if forces is not None:
                if any(force is None for force in forces):
                    raise ValueError(f"Frame at timestep {timestep} has missing force rows")
                frame_forces = [force for force in forces if force is not None]

            frames.append(
                LammpsDumpFrame(
                    frame_index=seen_frames,
                    timestep=timestep,
                    positions_nm=[pos for pos in positions if pos is not None],
                    box_nm=(box_nm[0], box_nm[1], box_nm[2]),
                    forces_ev_ang=frame_forces,
                )
            )
            if progress and (len(frames) == 1 or len(frames) % 10 == 0):
                _progress(
                    progress,
                    f"[active-learning] read {len(frames)} frame(s) "
                    f"(latest dump_frame={seen_frames}, step={timestep})",
                )
            seen_frames += 1

            if max_frames is not None and len(frames) >= max_frames:
                break

    _progress(progress, f"[active-learning] finished reading {len(frames)} frame(s)")
    return frames


def _read_random_lammps_dump_frames(
    path: Path,
    frame_stride: int,
    max_frames: int | None,
    random_frame_samples: int,
    random_seed: int,
    progress: bool,
) -> list[LammpsDumpFrame]:
    offsets: list[tuple[int, int]] = []
    seen_frames = 0
    eligible_frames = 0
    file_size = max(path.stat().st_size, 1)
    last_report_percent = -5

    _progress(progress, f"[active-learning] scanning dump frame offsets in {path}")
    with path.open("r", encoding="utf-8") as handle:
        while True:
            offset = handle.tell()
            line = handle.readline()
            if not line:
                break
            if not line.startswith("ITEM: TIMESTEP"):
                continue

            handle.readline()
            _expect_item(handle.readline(), "ITEM: NUMBER OF ATOMS")
            natoms = int(handle.readline().strip())
            _expect_item(handle.readline(), "ITEM: BOX BOUNDS")
            for _ in range(3):
                handle.readline()
            _expect_item(handle.readline(), "ITEM: ATOMS")
            for _ in range(natoms):
                handle.readline()

            if seen_frames % frame_stride == 0:
                if max_frames is not None and eligible_frames >= max_frames:
                    break
                offsets.append((seen_frames, offset))
                eligible_frames += 1
            seen_frames += 1
            percent = int(handle.tell() * 100 / file_size)
            if progress and percent >= last_report_percent + 5:
                last_report_percent = percent
                _progress(
                    progress,
                    "[active-learning] scanning dump offsets: {}% "
                    "(seen_frames={}, eligible_frames={})".format(
                        min(percent, 100),
                        seen_frames,
                        eligible_frames,
                    ),
                )

    rng = random.Random(random_seed)
    total_eligible = len(offsets)
    if len(offsets) > random_frame_samples:
        offsets = sorted(rng.sample(offsets, random_frame_samples), key=lambda item: item[0])
    _progress(
        progress,
        "[active-learning] selected {}/{} eligible frame(s) for detailed reading".format(
            len(offsets),
            total_eligible,
        ),
    )

    frames: list[LammpsDumpFrame] = []
    with path.open("r", encoding="utf-8") as handle:
        for selected_number, (frame_index, offset) in enumerate(offsets, start=1):
            _progress(
                progress,
                "[active-learning] reading selected frame {}/{} (dump_frame={})".format(
                    selected_number,
                    len(offsets),
                    frame_index,
                ),
            )
            handle.seek(offset)
            frames.append(_read_lammps_dump_frame_at_current_position(handle, frame_index))

    _progress(progress, f"[active-learning] finished reading {len(frames)} selected frame(s)")
    return frames


def _read_lammps_dump_frame_at_current_position(handle, frame_index: int) -> LammpsDumpFrame:
    _expect_item(handle.readline(), "ITEM: TIMESTEP")
    timestep = int(handle.readline().strip())
    _expect_item(handle.readline(), "ITEM: NUMBER OF ATOMS")
    natoms = int(handle.readline().strip())
    box_header = handle.readline().strip()
    _expect_item(box_header, "ITEM: BOX BOUNDS")
    box_bounds = [_parse_box_bound(handle.readline()) for _ in range(3)]
    box_nm = tuple((hi - lo) / 10.0 for lo, hi in box_bounds)

    atom_header = handle.readline().strip()
    _expect_item(atom_header, "ITEM: ATOMS")
    columns = atom_header.split()[2:]

    positions: list[Vector | None] = [None] * natoms
    forces: list[Vector | None] | None = (
        [None] * natoms if all(name in columns for name in ("fx", "fy", "fz")) else None
    )

    col = {name: index for index, name in enumerate(columns)}
    coord_mode = _coordinate_mode(columns)
    for _ in range(natoms):
        parts = handle.readline().split()
        atom_id = int(parts[col["id"]]) - 1
        if atom_id < 0 or atom_id >= natoms:
            raise ValueError(f"Atom id {atom_id + 1} is outside 1..{natoms}")
        positions[atom_id] = _read_position_nm(parts, col, coord_mode, box_bounds)
        if forces is not None:
            forces[atom_id] = (
                float(parts[col["fx"]]),
                float(parts[col["fy"]]),
                float(parts[col["fz"]]),
            )

    if any(pos is None for pos in positions):
        raise ValueError(f"Frame at timestep {timestep} has missing atom ids")

    frame_forces: list[Vector] | None = None
    if forces is not None:
        if any(force is None for force in forces):
            raise ValueError(f"Frame at timestep {timestep} has missing force rows")
        frame_forces = [force for force in forces if force is not None]

    return LammpsDumpFrame(
        frame_index=frame_index,
        timestep=timestep,
        positions_nm=[pos for pos in positions if pos is not None],
        box_nm=(box_nm[0], box_nm[1], box_nm[2]),
        forces_ev_ang=frame_forces,
    )


def write_active_cluster_xyz(
    path: str | Path,
    atoms: Sequence[AtomRecord],
    molecules: Sequence[MoleculeRecord],
    candidate: _ActiveCandidate,
) -> None:
    """Write a selected active-learning cluster as centered XYZ in Angstrom."""

    path = Path(path)
    frame = FrameData(
        frame_index=candidate.frame.frame_index,
        time_ps=None,
        positions_nm=candidate.frame.positions_nm,
        box_nm=candidate.frame.box_nm,
    )
    geometries = _molecule_geometries(frame, molecules)
    seed_center = geometries[candidate.mol_indices[0]].center

    cluster_atoms: list[tuple[str, Vector]] = []
    for mol_index in candidate.mol_indices:
        mol = molecules[mol_index]
        mol_center = geometries[mol_index].center
        delta = minimum_image_delta(seed_center, mol_center, frame.box_nm)
        target_center = add(seed_center, delta)
        shift = sub(target_center, mol_center)
        unwrapped_positions = _unwrapped_molecule_positions(frame, mol, mol.atom_indices)
        for atom_index in mol.atom_indices:
            pos_nm = add(unwrapped_positions[atom_index], shift)
            cluster_atoms.append((atoms[atom_index].element, scale(pos_nm, 10.0)))

    center_ang = mean_vector([pos for _, pos in cluster_atoms])
    centered_atoms = [(element, sub(pos, center_ang)) for element, pos in cluster_atoms]

    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(f"{len(centered_atoms)}\n")
        handle.write(
            "active_learning score={:.6f} step={} frame={} cluster_size={} residues={} "
            "max_force_ev_ang={:.6f} rms_force_ev_ang={:.6f} min_dist_ang={:.6f}\n".format(
                candidate.score,
                candidate.frame.timestep,
                candidate.frame.frame_index,
                len(candidate.mol_indices),
                ",".join(str(molecules[i].resid) for i in candidate.mol_indices),
                candidate.max_force_ev_ang,
                candidate.rms_force_ev_ang,
                candidate.min_interatomic_distance_nm * 10.0,
            )
        )
        for element, pos in centered_atoms:
            handle.write(f"{element:2s} {pos[0]:14.8f} {pos[1]:14.8f} {pos[2]:14.8f}\n")


def _frame_active_candidates(
    frame: LammpsDumpFrame,
    molecules: Sequence[MoleculeRecord],
    cluster_size: int,
    neighbor_pool: int,
    candidate_seeds_per_frame: int | None,
    contact_cutoff_nm: float,
    close_contact_alert_nm: float,
    hard_reject_distance_nm: float,
    rng: random.Random,
    progress: bool = False,
) -> list[_ActiveCandidate]:
    geometry_frame = FrameData(
        frame_index=frame.frame_index,
        time_ps=None,
        positions_nm=frame.positions_nm,
        box_nm=frame.box_nm,
    )
    geometries = _molecule_geometries(geometry_frame, molecules)
    neighbor_pool = max(cluster_size - 1, neighbor_pool)
    seen: set[tuple[int, ...]] = set()
    rough: list[tuple[float, tuple[int, ...]]] = []
    seed_indices = list(range(len(geometries)))
    if candidate_seeds_per_frame is not None and candidate_seeds_per_frame < len(seed_indices):
        seed_indices = sorted(rng.sample(seed_indices, candidate_seeds_per_frame))

    for seed_number, seed_index in enumerate(seed_indices, start=1):
        if progress and (seed_number == 1 or seed_number % 25 == 0 or seed_number == len(seed_indices)):
            _progress(
                progress,
                "[active-learning]   seed search {}/{} "
                "(frame={}, rough_candidates={})".format(
                    seed_number,
                    len(seed_indices),
                    frame.frame_index,
                    len(rough),
                ),
            )
        seed_geom = geometries[seed_index]
        neighbors: list[tuple[float, int]] = []
        for other_index, other_geom in enumerate(geometries):
            if seed_index == other_index:
                continue
            dist = norm(minimum_image_delta(seed_geom.center, other_geom.center, frame.box_nm))
            neighbors.append((dist, other_index))
        neighbors.sort(key=lambda item: item[0])
        pool = [index for _, index in neighbors[:neighbor_pool]]

        for combo in itertools.combinations(pool, cluster_size - 1):
            mol_indices = tuple(sorted((seed_index, *combo)))
            if mol_indices in seen:
                continue
            seen.add(mol_indices)
            pair_dists = [
                norm(minimum_image_delta(geometries[i].center, geometries[j].center, frame.box_nm))
                for i, j in itertools.combinations(mol_indices, 2)
            ]
            compactness = sum(pair_dists) / len(pair_dists)
            rough.append((compactness + rng.random() * 1e-9, mol_indices))

    max_rough = max(6000, 700 * cluster_size)
    rough.sort(key=lambda item: item[0])
    pair_cache: dict[tuple[int, int], dict[str, float]] = {}
    candidates: list[_ActiveCandidate] = []
    rough_to_score = rough[:max_rough]
    _progress(
        progress,
        "[active-learning]   scoring {} rough candidate(s) for frame {}".format(
            len(rough_to_score),
            frame.frame_index,
        ),
    )
    for rough_number, (_, mol_indices) in enumerate(rough_to_score, start=1):
        candidate = _score_active_candidate(
            frame=frame,
            geometry_frame=geometry_frame,
            molecules=molecules,
            geometries=geometries,
            mol_indices=mol_indices,
            contact_cutoff_nm=contact_cutoff_nm,
            close_contact_alert_nm=close_contact_alert_nm,
            hard_reject_distance_nm=hard_reject_distance_nm,
            pair_cache=pair_cache,
        )
        if candidate is not None:
            candidates.append(candidate)
        if progress and (
            rough_number == 1 or rough_number % 1000 == 0 or rough_number == len(rough_to_score)
        ):
            _progress(
                progress,
                "[active-learning]   contact scoring {}/{} "
                "(frame={}, accepted={})".format(
                    rough_number,
                    len(rough_to_score),
                    frame.frame_index,
                    len(candidates),
                ),
            )

    return candidates


def _score_active_candidate(
    frame: LammpsDumpFrame,
    geometry_frame: FrameData,
    molecules: Sequence[MoleculeRecord],
    geometries: Sequence,
    mol_indices: tuple[int, ...],
    contact_cutoff_nm: float,
    close_contact_alert_nm: float,
    hard_reject_distance_nm: float,
    pair_cache: dict[tuple[int, int], dict[str, float]],
) -> _ActiveCandidate | None:
    pair_metrics = []
    for i, j in itertools.combinations(mol_indices, 2):
        pair_key = (i, j) if i < j else (j, i)
        if pair_key not in pair_cache:
            pair_cache[pair_key] = _pair_active_metrics(
                geometry_frame,
                molecules[i],
                molecules[j],
                geometries[i],
                geometries[j],
                contact_cutoff_nm,
            )
        metrics = pair_cache[pair_key]
        if metrics["min_distance"] < hard_reject_distance_nm:
            return None
        pair_metrics.append(metrics)

    if not _is_contact_connected(mol_indices, pair_metrics, contact_cutoff_nm):
        return None

    cluster_atom_indices = list(
        itertools.chain.from_iterable(molecules[i].atom_indices for i in mol_indices)
    )
    force_mags = _cluster_force_magnitudes(frame.forces_ev_ang, cluster_atom_indices)
    max_force = max(force_mags) if force_mags else 0.0
    rms_force = math.sqrt(sum(value * value for value in force_mags) / len(force_mags)) if force_mags else 0.0

    avg_com = sum(metric["com_distance"] for metric in pair_metrics) / len(pair_metrics)
    min_dist = min(metric["min_distance"] for metric in pair_metrics)
    avg_contacts = sum(metric["contact_count"] for metric in pair_metrics) / len(pair_metrics)
    close_alert = min_dist <= close_contact_alert_nm
    compact_score = 1.0 / (1.0 + avg_com)

    return _ActiveCandidate(
        frame=frame,
        mol_indices=mol_indices,
        score=0.0,
        max_force_ev_ang=max_force,
        rms_force_ev_ang=rms_force,
        min_interatomic_distance_nm=min_dist,
        avg_pair_com_distance_nm=avg_com,
        avg_contact_count=avg_contacts,
        close_contact_alert=close_alert,
        compact_score=compact_score,
        feature=(),
    )


def _pair_active_metrics(
    frame: FrameData,
    mol_a: MoleculeRecord,
    mol_b: MoleculeRecord,
    geom_a,
    geom_b,
    contact_cutoff_nm: float,
) -> dict[str, float]:
    com_distance = norm(minimum_image_delta(geom_a.center, geom_b.center, frame.box_nm))
    min_distance = float("inf")
    contact_count = 0

    for atom_i in mol_a.heavy_atom_indices:
        pos_i = frame.positions_nm[atom_i]
        for atom_j in mol_b.heavy_atom_indices:
            distance = norm(minimum_image_delta(pos_i, frame.positions_nm[atom_j], frame.box_nm))
            if distance < min_distance:
                min_distance = distance
            if distance <= contact_cutoff_nm:
                contact_count += 1

    return {
        "com_distance": com_distance,
        "min_distance": min_distance,
        "contact_count": float(contact_count),
    }


def _assign_active_scores(candidates: Sequence[_ActiveCandidate]) -> None:
    max_force_scale = _robust_high_scale(candidate.max_force_ev_ang for candidate in candidates)
    rms_force_scale = _robust_high_scale(candidate.rms_force_ev_ang for candidate in candidates)
    contact_scale = _robust_high_scale(candidate.avg_contact_count for candidate in candidates)
    max_frame = max(candidate.frame.frame_index for candidate in candidates) or 1

    for candidate in candidates:
        norm_max_force = min(candidate.max_force_ev_ang / max_force_scale, 1.5)
        norm_rms_force = min(candidate.rms_force_ev_ang / rms_force_scale, 1.5)
        norm_contacts = min(candidate.avg_contact_count / contact_scale, 1.5)
        close_score = 1.0 if candidate.close_contact_alert else 0.0

        candidate.score = (
            0.42 * min(norm_max_force, 1.0)
            + 0.24 * min(norm_rms_force, 1.0)
            + 0.18 * min(norm_contacts, 1.0)
            + 0.10 * candidate.compact_score
            + 0.06 * close_score
        )
        candidate.feature = (
            norm_max_force,
            norm_rms_force,
            candidate.min_interatomic_distance_nm * 8.0,
            candidate.avg_pair_com_distance_nm,
            norm_contacts,
            candidate.frame.frame_index / max_frame,
        )


def _select_diverse_active_candidates(
    candidates: Sequence[_ActiveCandidate],
    n_samples: int,
) -> list[_ActiveCandidate]:
    ranked = sorted(candidates, key=lambda candidate: candidate.score, reverse=True)
    selected = [ranked[0]]
    remaining = ranked[1:]

    while remaining and len(selected) < n_samples:
        best_index = 0
        best_value = -float("inf")
        for index, candidate in enumerate(remaining):
            diversity = min(_feature_distance(candidate.feature, item.feature) for item in selected)
            overlap = max(_molecule_overlap(candidate.mol_indices, item.mol_indices) for item in selected)
            value = 0.72 * candidate.score + 0.28 * min(diversity, 1.0) - 0.18 * overlap
            if value > best_value:
                best_value = value
                best_index = index
        selected.append(remaining.pop(best_index))

    return selected


def _is_contact_connected(
    mol_indices: tuple[int, ...],
    pair_metrics: Sequence[dict[str, float]],
    contact_cutoff_nm: float,
) -> bool:
    parent = {index: index for index in mol_indices}

    def find(index: int) -> int:
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    def union(a: int, b: int) -> None:
        root_a = find(a)
        root_b = find(b)
        if root_a != root_b:
            parent[root_b] = root_a

    for (i, j), metrics in zip(itertools.combinations(mol_indices, 2), pair_metrics):
        if metrics["min_distance"] <= contact_cutoff_nm or metrics["com_distance"] <= 1.20:
            union(i, j)

    return len({find(index) for index in mol_indices}) == 1


def _cluster_force_magnitudes(
    forces_ev_ang: Sequence[Vector] | None,
    atom_indices: Sequence[int],
) -> list[float]:
    if forces_ev_ang is None:
        return []
    return [norm(forces_ev_ang[index]) for index in atom_indices]


def _molecule_overlap(a: Sequence[int], b: Sequence[int]) -> float:
    if not a:
        return 0.0
    return len(set(a) & set(b)) / len(set(a))


def _robust_high_scale(values: Iterable[float]) -> float:
    sorted_values = sorted(float(value) for value in values)
    if not sorted_values:
        return 1.0
    index = min(len(sorted_values) - 1, max(0, int(0.95 * (len(sorted_values) - 1))))
    return max(sorted_values[index], 1e-12)


def _feature_distance(a: Sequence[float], b: Sequence[float]) -> float:
    length = min(len(a), len(b))
    if length == 0:
        return 0.0
    return math.sqrt(sum((a[i] - b[i]) ** 2 for i in range(length)) / length)


def _write_active_metadata(output_dir: Path, samples: Sequence[ActiveLearningSample]) -> None:
    json_path = output_dir / "active_learning_samples.json"
    csv_path = output_dir / "active_learning_samples.csv"

    with json_path.open("w", encoding="utf-8", newline="\n") as handle:
        json.dump([asdict(sample) for sample in samples], handle, indent=2)
        handle.write("\n")

    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(ActiveLearningSample.__dataclass_fields__))
        writer.writeheader()
        for sample in samples:
            row = asdict(sample)
            row["molecule_resids"] = " ".join(str(item) for item in sample.molecule_resids)
            writer.writerow(row)


def _coordinate_mode(columns: Sequence[str]) -> str:
    for mode in ("x", "xu", "xs"):
        names = (mode, mode.replace("x", "y", 1), mode.replace("x", "z", 1))
        if all(name in columns for name in names):
            return mode
    raise ValueError("LAMMPS dump must contain x/y/z, xu/yu/zu, or xs/ys/zs columns")


def _read_position_nm(
    parts: Sequence[str],
    col: dict[str, int],
    coord_mode: str,
    box_bounds: Sequence[tuple[float, float]],
) -> Vector:
    if coord_mode == "x":
        return (
            float(parts[col["x"]]) / 10.0,
            float(parts[col["y"]]) / 10.0,
            float(parts[col["z"]]) / 10.0,
        )
    if coord_mode == "xu":
        return (
            float(parts[col["xu"]]) / 10.0,
            float(parts[col["yu"]]) / 10.0,
            float(parts[col["zu"]]) / 10.0,
        )

    coords = []
    for axis, (lo, hi) in zip(("xs", "ys", "zs"), box_bounds):
        coords.append((lo + float(parts[col[axis]]) * (hi - lo)) / 10.0)
    return (coords[0], coords[1], coords[2])


def _parse_box_bound(line: str) -> tuple[float, float]:
    fields = line.split()
    if len(fields) < 2:
        raise ValueError(f"Invalid BOX BOUNDS line: {line!r}")
    return float(fields[0]), float(fields[1])


def _expect_item(line: str, prefix: str) -> None:
    if not line.startswith(prefix):
        raise ValueError(f"Expected {prefix!r}, got {line.strip()!r}")
